[tool.poetry]
name = "obsidian-test"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.9"
beautifulsoup4 = "^4.12.3"
typer = {extras = ["all"], version = "^0.12.3"}
requests = "2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

